image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    command: cd FridgeManager;mvn install;mvn javafx:run -f fxui/pom.xml


ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
